version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network

  flask:
    build: .
    container_name: flask-app
    ports:
      - "5006:5006"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/Cluster0
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
